---
kind: pipeline
name: container

platform:
  os: linux
  arch: amd64

steps:

- name: tags
  image: alpine
  commands:
  - export BASE=${DRONE_TAG:-latest}
  - export TAG=$${BASE##v}
  - if [ "$$TAG" == "latest" ]; then echo -n "latest" > .tags; else echo -n "latest,$${TAG},$${TAG%-*},$${TAG%.*},$${TAG%%.*}" > .tags; fi

- name: publish
  image: plugins/docker
  settings:
    build_args:
    - BUILD_VERSION=${DRONE_TAG%-*}
    repo: webhippie/${DRONE_REPO_NAME}
    dockerfile: deployments/Dockerfile
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username

- name: readme
  image: sheogorath/readme-to-dockerhub
  environment:
    DOCKERHUB_PASSWORD:
      from_secret: docker_password
    DOCKERHUB_REPO_NAME: ${DRONE_REPO_NAME}
    DOCKERHUB_REPO_PREFIX: webhippie
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    README_PATH: README.md

---
  kind: pipeline
  type: ssh
  name: deployment

  server:
    host: 159.69.36.250
    user:
      from_secret: drone_user_name
    password:
      from_secret: drone_user_password

  steps:
  - name: pull latest image
    commands:
    - docker pull webhippie/hubbot:latest

  - name: restart compose stack
    commands:
    - docker-compose -f /opt/hubbot/docker-compose.yml down
    - docker-compose f /opt/hubbot/docker-compose.yml up -d