---
kind: pipeline
name: container

platform:
  os: linux
  arch: amd64

steps:

- name: tags
  image: alpine
  commands:
  - export BASE=${DRONE_TAG:-latest}
  - export TAG=$${BASE##v}
  - if [ "$$TAG" == "latest" ]; then echo -n "latest" > .tags; else echo -n "latest,$${TAG},$${TAG%-*},$${TAG%.*},$${TAG%%.*}" > .tags; fi

- name: publish
  image: plugins/docker
  settings:
    build_args:
    - BUILD_VERSION=${DRONE_TAG%-*}
    repo: webhippie/${DRONE_REPO_NAME}
    dockerfile: deployments/Dockerfile
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username

- name: readme
  image: sheogorath/readme-to-dockerhub
  environment:
    DOCKERHUB_PASSWORD:
      from_secret: docker_password
    DOCKERHUB_REPO_NAME: ${DRONE_REPO_NAME}
    DOCKERHUB_REPO_PREFIX: webhippie
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    README_PATH: README.md

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: host
    username:
      from_secret: user
    password:
      from_secret: password
    port: 22
    script:
      - docker pull webhippie/hubbot:latest
      - cd /opt/hubbot
      - docker-compose rm -sf hubbot
      - docker-compose up -d hubbot
